import { useState } from 'react';
import { ArrowLeft, CalendarDays, MapPin } from 'lucide-react';
import ControlRoomSidebar from '../components/ControlRoomSidebar';
import { incidents } from '../data/indiaIncidents';

export default function ControlRoomIncidentHistory() {
  const [selectedId, setSelectedId] = useState(null);
  const selected = incidents.find((incident) => incident.id === selectedId);
  return <div className="crs-layout"><ControlRoomSidebar active="history" /><main className="crs-main cr-data-page"><header className="cr-data-page__header"><div><p className="cr-overview__eyebrow">ARCHIVED EVENTS</p><h1>INCIDENT HISTORY</h1><p>Review completed and previously monitored hazards with their full incident record.</p></div>{selected && <button className="control-room-secondary-button" onClick={() => setSelectedId(null)} type="button"><ArrowLeft size={14} /> All incidents</button>}</header>{selected ? <article className="cr-incident-detail"><div className="cr-detail-page__intro"><div><p className="cr-overview__eyebrow">INCIDENT RECORD</p><h2>{selected.hazard} · {selected.region}</h2><p><MapPin size={14} /> {selected.location}</p></div><span className={`severity-badge severity-badge--${selected.tone}`}>{selected.severity}</span></div><div className="cr-incident-detail__summary"><div><span>Population at risk</span><strong>{selected.populationAtRisk}</strong></div><div><span>Status</span><strong>{selected.status}</strong></div><div><span>Response action</span><strong>{selected.action}</strong></div></div><p className="cr-incident-detail__reason">{selected.reason}</p><h3>Recorded measurements</h3><dl className="cr-measurements">{selected.measurements.map((measurement) => <div key={measurement.label}><dt>{measurement.label}</dt><dd>{measurement.value}</dd></div>)}</dl></article> : <section className="cr-data-grid" aria-label="Historical incidents">{incidents.map((incident) => <button className="cr-data-card cr-data-card--button" key={incident.id} onClick={() => setSelectedId(incident.id)} type="button"><div className="cr-data-card__eyebrow"><CalendarDays size={14} /> {incident.status}</div><h2>{incident.hazard}</h2><p>{incident.location}</p><strong>{incident.severity} · {incident.populationAtRisk} people at risk</strong><span>View full incident record →</span></button>)}</section>}</main></div>;
}